platform :ios, '13.0'

use_frameworks!

#
# Install from local parent directory.
#
pod "SwiftPrettyPrint", :path => "../", :branch => "feature/combine-example", :configuration => "Debug"

#
# Typical: install from CocoaPods repository.
#
# pod "SwiftPrettyPrint", :configuration => "Debug"

target 'SwiftPrettyPrintExample' do
  target 'SwiftPrettyPrintExampleTests' do
    inherit! :search_paths
  end
end
