platform :ios, '13.0'

use_frameworks!

pod "SwiftPrettyPrint", :configuration => "Debug"

target 'SwiftPrettyPrintExample' do
  target 'SwiftPrettyPrintExampleTests' do
    inherit! :search_paths
  end
end
