#if !canImport(ObjectiveC)
import XCTest

extension DebugTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DebugTests = [
        ("testLabel", testLabel),
        ("testMultipleValuesAndSeparator", testMultipleValuesAndSeparator),
        ("testPretyPrint", testPretyPrint),
        ("testPrint", testPrint),
    ]
}

extension MultilineFormatterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MultilineFormatterTests = [
        ("testCollectionString", testCollectionString),
        ("testDictionaryString", testDictionaryString),
        ("testObjectString", testObjectString),
        ("testTupleString", testTupleString),
    ]
}

extension OptionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OptionTests = [
        ("testExample", testExample),
    ]
}

extension PrettyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PrettyTests = [
        ("testExtractKeyValues", testExtractKeyValues),
        ("testString_BasicType", testString_BasicType),
        ("testString_Class", testString_Class),
        ("testString_Collection", testString_Collection),
        ("testString_Dictionary", testString_Dictionary),
        ("testString_Enum", testString_Enum),
        ("testString_Set", testString_Set),
        ("testString_Struct", testString_Struct),
        ("testString_Tuple", testString_Tuple),
    ]
}

extension SinglelineFormatterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SinglelineFormatterTests = [
        ("testCollectionString", testCollectionString),
        ("testDictionaryString", testDictionaryString),
        ("testObjectString", testObjectString),
        ("testTupleString", testTupleString),
    ]
}

extension String_extensionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__String_extensionTests = [
        ("testIndentTail", testIndentTail),
        ("testRemoveEnclosedParentheses", testRemoveEnclosedParentheses),
    ]
}

extension UtilTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UtilTests = [
        ("testPrefixLabel", testPrefixLabel),
        ("testPrefixLabelPretty", testPrefixLabelPretty),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DebugTests.__allTests__DebugTests),
        testCase(MultilineFormatterTests.__allTests__MultilineFormatterTests),
        testCase(OptionTests.__allTests__OptionTests),
        testCase(PrettyTests.__allTests__PrettyTests),
        testCase(SinglelineFormatterTests.__allTests__SinglelineFormatterTests),
        testCase(String_extensionTests.__allTests__String_extensionTests),
        testCase(UtilTests.__allTests__UtilTests),
    ]
}
#endif
