default_platform(:ios)

platform :ios do
  desc "Integration test to SwiftPrittyPrint"
  lane :test do
    run_tests(
      workspace: "./SwiftPrettyPrintExample.xcworkspace",
      scheme: "SwiftPrettyPrintExample"
    )
  end
end
